DROP DATABASE IF EXISTS ToDelete;
CREATE DATABASE IF NOT EXISTS ToDelete;
CREATE USER IF NOT EXISTS 'admin_service'@'%' IDENTIFIED BY 'N0Pa55wrd';
GRANT ALL ON ToDelete.* TO 'admin_service'@'%';
FLUSH PRIVILEGES;
